### ISSUE TITLE
feature request - multiple apis

### ISSUE THREAD

**Issue by tirzah2** [Vexthecollector/elevenlabs-for-foundry#5]
Hi!
I  try to put it out there..  would it be possible to modify the config page and have like a  + and - button and be able to add several api keys, and the system to select the one with the most characters all the time? this would make this module probably an immediate keeper!

**Comment by Vexthecollector** [comment]
Why would you need multiple api keys? If this is so you can as a group share keys better, that's something I'm currently working on.

**Comment by tirzah2** [comment]
For people like me that can't really afford a paid subscription, I might use the free one, and then the api key of the assistant game master, then api key made by a player Etcetc.
And because I have put the playsound on a trigger with a high DC that generates random sentences to be read by random voices, the players may eventually empty the characters monthly allowance and it would be nice to have few api keys as a reserve in case it happens. Peace of mind basically.

**Comment by Vexthecollector** [comment]
You can't use the api with a free key, furthermore it is against tos to create multiple free accounts
